---
- name: Fetch assets from EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    s3_bucket_name: ""
    s3_object_key: "assets.tar"
    destination_directory: "/var/www/html"
    temp_directory: "/var/www/html/build"

  tasks:
     - name: Get EC2 instances with tag "frontend"
       ec2_instance_info:
        region: "ap-south-1"
        filters:
          "tag:Name": "Frontend"
          instance-state-name: "running"
       register: ec2_instances
       become: yes
       become_user: ubuntu

     - name: Print IP addresses of EC2 instances
       debug:
         msg: "IP Address of EC2 instance {{ item.public_ip_address }}"
       with_items: "{{ ec2_instances.instances }}"

     - name: Remove all items in destination directory
       file:
         path: "{{ destination_directory }}"
         state: absent
       become: yes

     - name: Create build directory inside /var/www/html
       file:
        path: "{{ temp_directory }}"
        state: directory
       become: yes


     - name: Download file from S3
       get_url:
          url: "https://{{ s3_bucket_name }}.s3.amazonaws.com/{{ s3_object_key }}"
          dest: "{{ destination_directory }}/assets.tar"
       delegate_to: "{{ item.public_ip_address }}"
       with_items: "{{ ec2_instances.instances }}"
       register: download_result


     - name: Unzip assets.zip to temporary directory
       unarchive:
         src: "{{ destination_directory }}/assets.tar"
         dest: "{{ temp_directory }}"
         remote_src: yes
       become: yes
       delegate_to: "{{ item.public_ip_address }}"
       with_items: "{{ ec2_instances.instances }}"
   
     - name: Copy files and folders from build directory to /var/www/html
       copy:
          src: "{{ temp_directory }}/"
          dest: "{{ destination_directory }}"
          remote_src: yes
       delegate_to: "{{ item.public_ip_address }}"
       with_items: "{{ ec2_instances.instances }}"
       become: yes
       become_user: root
